#!/bin/bash

alias la='ls -la'
alias rm='rm -i'
alias cp='cp -i'
alias find='fd'
alias less='less -r'
alias z='source ~/.zshrc'
alias a='source ~/.aliases'
alias vi=vim
alias v=vim
function cdls
  cd $argv;
  ls;
end
alias ts='ts "[%H:%M:%S]"' #http://joeyh.name/code/moreutils/
alias cdl='cd (pwd -P)'
alias cs='cdls'
alias dul='du -ah * | sort -r -n | head -10'

# Recursive search and replace

# $1 = file pattern e.g. *.go
# $2 = old string
# $3 new string
# e.g. sandr .go Sirupsen sirupsen
function sandr
  find . -name $1 -print0 | xargs -0 sed -i "" "s/$2/$3/g"
end
# Tmux
alias tn="tmux new -s"
alias ta="tmux attach -t"
alias tl="tmux list-sessions"

# Git
alias gb="git branch"
alias gbl="git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - (%(color:green)%(committerdate:relative)%(color:reset))'"
alias gbv="git branch -vv"
alias ga="git add -u"
alias gaa="git add -A"
alias gc="git checkout"
alias gcb="git checkout -b"
# alias gl="git log-compact --decorate"
# alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias gl="tig"
alias gs="git status -s"
alias gd="git diff"
alias gdn="git diff --name-only"
alias gdt="git difftool -y"
alias gdtm="git difftool -y origin/master"
alias gdtf="git difftool -y --tool=fugitive"
alias gdtc="git difftool -y --cached"
alias gdtcf="git difftool -y --cached --tool=fugitive"
alias gclean="git remote prune origin;git gc"
alias gu="git up"
alias gpm="git pull origin master"
alias gpush="git push"
alias grh="git reset HEAD"
alias gsta="git stash save -u"
alias gstp="git stash pop"
alias gstl="git stash list"
alias gsts="git stash show -p"
# More obscure git commands
alias gignored='git ls-files --others -i --exclude-standard | grep -vE ^vendor'


# open the files that were modified in a specified commit
function gedit
  vim -O (git show --pretty=format: --name-only $1 | sed '$!N; s/\n/ /;')
end
# built-in to omzsh - git stash clear
# unalias gstc

# Docker
# https://github.com/jesseduffield/lazydocker/blob/master/README.md
alias lzd='lazydocker'
alias dgui="echo 'Starting Docker GUI on http://localhost:9000' && docker run -d --name docker_gui -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer"
alias dclean='docker system prune --volumes'
alias ddf='docker system df'
alias di='docker images'
alias dh='docker history --no-trunc'
alias drmi='docker rmi -f'
alias drmid='docker rmi (docker images -f "dangling=true" -q)'
alias dps='docker ps -a'
alias dstopa='docker stop (docker ps -aq)'
alias dr='docker run'
alias drma='docker rm (docker ps -aq -f status=exited -f status=created)'
alias drm='docker rm'
alias dvls='docker volume ls'
alias dvrma='docker volume rm (docker volume ls -q)'
alias dcup='docker-compose up'
alias dcdown='docker-compose down -v'
alias dclogs='docker-compose logs'
alias dcexec='docker-compose exec'
function drmii
  docker rmi -f (docker images $1 -q | uniq)
end
function dsh # run a shell from an image
    docker run -ti --entrypoint="" $1 sh
end
function dcsh
    docker-compose exec $1 sh
end

# Kubernetes
alias k='kubectl'
alias kuc='kubectl config use-context'
alias kc='kubectl config get-contexts'
alias kp='kubectl get po'
alias kd='kubectl describe pod'
alias kcp='kubectl cp'
alias ke='kubectl exec'
function ksh
  kubectl exec -ti $1 sh
end

# Ruby
alias be='bundle exec'
if which rbenv > /dev/null; then eval "(rbenv init -)"; end
