export ZSH="/Users/jgostelow/.oh-my-zsh"

zmodload zsh/zprof

# plugins
# https://github.com/zsh-users/antigen
source ~/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle git
antigen bundle dirhistory
#antigen bundle jsontools
#antigen bundle rbenv
antigen apply

ZSH_THEME="af-magic"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
plugins=(dirhistory git zsh-autosuggestions zsh-syntax-highlighting)

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
unsetopt correct_all

# Do not share history across sessions
unsetopt share_history

PATH=~/bin:$PATH
export EDITOR='vim'

source $ZSH/oh-my-zsh.sh
source ~/.aliases
