export ZSH="$HOME/.oh-my-zsh"
plugins=(git)
# source $ZSH/oh-my-zsh.sh

# to profile zsh speed
zmodload zsh/zprof
# zprof

COMPLETION_WAITING_DOTS="true"

## Plugins
# https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
source $HOME/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle RobertDeRose/virtualenv-autodetect
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen apply

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Do not autocorrect commands
#ENABLE_CORRECTION="true"
unsetopt correct_all
unsetopt correct
DISABLE_AUTO_TITLE="true"

# Do not share history across sessions
unsetopt share_history
setopt no_share_history

PATH=~/bin:$PATH

# VIM mode (ctrl-a, ctrl-e does not work)
#export EDITOR='vim'
#bindkey -v

# fzf
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# https://ohmyposh.dev/docs/themes
#eval "$(oh-my-posh init zsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/craver.omp.json)"
#eval "$(oh-my-posh init zsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/atomic.omp.json)"

#eval "$(oh-my-posh init zsh --config /Users/jgostelow/dotfiles/zsh/themes/easy-term-custom.omp.json)"
eval "$(oh-my-posh init zsh --config /Users/jgostelow/dotfiles/zsh/themes/craver.omp.json)"

source ~/.aliases
