export ZSH=$HOME/.oh-my-zsh

zmodload zsh/zprof

COMPLETION_WAITING_DOTS="true"

## Plugins
# https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
source $(brew --prefix)/share/antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen apply

# https://ohmyposh.dev/docs/themes
eval "$(oh-my-posh init zsh --config $HOME/GIT/dotfiles/zsh/sonicboom_light.custom.omp.json)"
# eval "$(oh-my-posh init zsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/sonicboom_light.omp.json)"

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Do not autocorrect commands
#ENABLE_CORRECTION="true"
unsetopt correct_all
unsetopt correct
DISABLE_AUTO_TITLE="true"

# Do not share history across sessions
unsetopt share_history
setopt no_share_history

PATH=~/bin:$PATH
export EDITOR='vim'

# VIM mode
bindkey -v

source $ZSH/oh-my-zsh.sh
source ~/.aliases

# fzf
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
