export ZSH=$HOME/.oh-my-zsh

zmodload zsh/zprof

# plugins
# https://github.com/zsh-users/antigen
source ~/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle git
antigen bundle docker
antigen bundle docker-compose
#antigen theme romkatv/powerlevel10k
antigen apply

eval "$(starship init zsh)"

# ZSH_THEME="jono" # base on amuse, added a horizontal line

COMPLETION_WAITING_DOTS="true"

# https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
plugins=(dirhistory git kubectl)

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Do not autocorrect commands
#ENABLE_CORRECTION="true"
unsetopt correct_all
unsetopt correct
DISABLE_AUTO_TITLE="true"

# Do not share history across sessions
unsetopt share_history

PATH=~/bin:$PATH
export EDITOR='vim'

# VIM mode
bindkey -v

source $ZSH/oh-my-zsh.sh
source ~/.aliases
